import { z } from 'zod'

export const MOBILE_WEB_BRIDGE_OPERATIONS = {
  workspace: [
    'snapshot',
    'repositories',
    'subscribe',
    'activate',
    'update',
    'remove',
    'creationRepositories',
    'creationRetiredNames',
    'creationSettings',
    'creationTrustedHooks',
    'creationGitLabAvailability',
    'creationLinearAvailability',
    'creationSshState',
    'creationSshConnect',
    'creationDetectAgents',
    'creationRepoHooks',
    'creationRuntimeCapabilities',
    'creationSparsePresets',
    'creationSaveSparsePreset',
    'creationPersistTrust',
    'creationSearchGitHub',
    'creationSearchGitLab',
    'creationSearchLinear',
    'creationSearchBranches',
    'creationResolveRepoSlug',
    'creationLookupGitHub',
    'creationLookupGitHubRepo',
    'creationLookupGitLab',
    'creationResolvePrBase',
    'creationResolveMrBase',
    'creationCreateBlank',
    'creationCreateFromSource'
  ],
  session: [
    'capabilities',
    'snapshot',
    'subscribe',
    'agentOptions',
    'quickCommands',
    'quickCommandMutate',
    'create',
    'createAgent',
    'createQuickCommand',
    'createBrowser',
    'activate',
    'close'
  ],
  terminal: [
    'subscribe',
    'input',
    'queryReply',
    'clipboardPaste',
    'attachImage',
    'resize',
    'visibility',
    'displayMode',
    'clear',
    'rename',
    'resync',
    'ack',
    'cancel'
  ],
  file: [
    'list',
    'directory',
    'read',
    'readChunk',
    'search',
    'write',
    'markdownRead',
    'markdownSave',
    'markdownDraftRead',
    'markdownDraftWrite',
    'open',
    'resolveTerminalPath',
    'readTerminalArtifactChunk',
    'releaseTerminalArtifact'
  ],
  sourceControl: [
    'status',
    'diff',
    'subscribe',
    'stage',
    'unstage',
    'discard',
    'commit',
    'generateCommitMessage',
    'cancelCommitMessageGeneration',
    'branch',
    'branches',
    'history',
    'branchCompare',
    'commitCompare',
    'reviewMetadata',
    'reviewMetadataUpdate',
    'reviewLink',
    'reviewLinkUpdate',
    'reviewDiff',
    'reviewOpen',
    'reviewTerminalSend',
    'upstream',
    'fetch',
    'pull',
    'push',
    'rebase',
    'abort'
  ],
  task: [
    'bootstrap',
    'repositories',
    'linearContext',
    'resolveRepoSlug',
    'updateResume',
    'updateSettings',
    'listGitHub',
    'countGitHub',
    'listGitLab',
    'listGitLabTodos',
    'listLinear',
    'listGitHubLabels',
    'listGitHubAssignableUsers',
    'loadGitHubDetail',
    'loadGitLabDetail',
    'loadLinearDetail',
    'listProjects',
    'listProjectViews',
    'resolveProjectRef',
    'projectTable',
    'projectItemDetail',
    'projectItemLabels',
    'projectItemAssignableUsers',
    'projectIssueTypes',
    'updateProjectItem',
    'addProjectComment',
    'updateProjectComment',
    'deleteProjectComment',
    'updateProjectMetadata',
    'updateProjectField',
    'updateProjectIssueType',
    'resolveProjectReviewThread',
    'replyProjectReviewComment',
    'addProjectConversationComment',
    'requestProjectReviewers',
    'rerunProjectChecks',
    'mergeProjectPullRequest',
    'refreshProjectChecks',
    'setProjectFileViewed',
    'loadProjectFileContents',
    'addProjectInlineComment',
    'updateHostedTaskStatus',
    'updateHostedTaskMetadata',
    'addHostedTaskComment',
    'requestHostedTaskReviewers',
    'resolveHostedTaskReviewThread',
    'replyHostedTaskReviewComment',
    'mergeHostedTaskReview',
    'refreshHostedTaskChecks',
    'rerunHostedTaskChecks',
    'setHostedTaskFileViewed',
    'loadHostedTaskFileContents',
    'addHostedTaskInlineComment',
    'connectLinear',
    'listLinearTeams',
    'listLinearTeamStates',
    'selectLinearWorkspace',
    'updateLinearIssueState',
    'addLinearIssueComment',
    'loadLinearIssue',
    'createLinearSubIssue',
    'createLinearIssue',
    'createProviderIssue',
    'updateIssueSource'
  ],
  provider: [
    'review',
    'reviewCreationEligibility',
    'reviewCreate',
    'reviewGenerateFields',
    'reviewDiff',
    'reviewQuery',
    'mutateReview',
    'manageReview',
    'submitReview'
  ],
  browser: ['subscribe', 'navigate', 'back', 'forward', 'reload', 'dialog', 'pointer', 'keyboard'],
  account: ['snapshot', 'select', 'resetCreditCapability', 'consumeResetCredit', 'subscribe'],
  agentHistory: ['snapshot', 'preview', 'resume'],
  settings: ['snapshot', 'update'],
  speech: [
    'subscribe',
    'setup',
    'downloadModel',
    'deleteModel',
    'configure',
    'start',
    'stop',
    'cancel'
  ],
  native: [
    'alert',
    'hapticSelection',
    'hapticFeedback',
    'clipboardAvailability',
    'clipboardWrite',
    'openExternal',
    'terminalPreferences',
    'terminalAccessoryPreferences',
    'terminalCustomKeysUpdate',
    'terminalTextScaleUpdate',
    'sessionChatDraftRead',
    'sessionChatDraftWrite'
  ],
  nativeChat: [
    'read',
    'subscribe',
    'sendMessage',
    'prepareCommit',
    'respond',
    'stop',
    'attachImage',
    'pasteImages',
    'releaseImages',
    'pendingRead',
    'pendingWrite',
    'fileSearch',
    'openFile',
    'readability'
  ],
  navigation: ['route', 'reconnect', 'removeHost']
} as const

export const MobileWebBridgeCapabilitySchema = z.enum([
  'workspace',
  'session',
  'terminal',
  'file',
  'sourceControl',
  'task',
  'provider',
  'browser',
  'account',
  'agentHistory',
  'settings',
  'speech',
  'native',
  'nativeChat',
  'navigation'
])

export type MobileWebBridgeCapability = z.infer<typeof MobileWebBridgeCapabilitySchema>

/** Operation names a page may request for one capability. Keeps request clients from naming an
 * operation the shell never granted. */
export type MobileWebBridgeOperationName<
  TCapability extends MobileWebBridgeCapability = MobileWebBridgeCapability
> = (typeof MOBILE_WEB_BRIDGE_OPERATIONS)[TCapability][number]

export function isMobileWebBridgeOperation(
  capability: MobileWebBridgeCapability,
  operation: string
): boolean {
  return (MOBILE_WEB_BRIDGE_OPERATIONS[capability] as readonly string[]).includes(operation)
}
